arpstrap/urls.py
from django.conf.urls import include, url

from .views import PostDetail, PostList


app_name = 'blog'

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name='blog',
        ),
    url(r'page/(?P<page>[\d])/$',
        PostList.as_view(),
        name='blog',
        ),
    url(r'^post/(?P<slug>[\w\d-]+)/$',
        PostDetail.as_view(),
        name='post'
        ),
]

blog/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('arpstrap.urls')),
    url(r'^category/', include('arpegio.categories.urls')),
    url(r'^tag/', include('arpegio.tags.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + (static(settings.MEDIA_URL,
                                        document_root=settings.MEDIA_ROOT))
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

arpstrap/models.py
from django.db import models
from arpegio.blog.models import Post as arpegio_Post
from arpegio.blog.managers import PostManager
from arpegio.categories.models import Categorizable
from arpegio.tags.models import Taggable

class Post(arpegio_Post, Categorizable, Taggable):
    """The custom post model."""
    objects = PostManager()

arpstrap/views.py
from arpegio.blog import views

from .models import Post


class PostList(views.PostList):
    model = Post


class PostDetail(views.PostDetail):
    model = Post

arpstrap/templates/arpegio-blog/base.html
{% extends 'arpegio-core/base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      {% block main_content %}
      {% endblock %}

      {% block sidebar %}
        {% include 'arpegio-blog/includes/sidebar.html' %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

arpstrap/templates/arpegio-blog/includes/posts_list.html
{% load arpegio_tags %}
{% for post in posts %}
<div class="blog-post" id="post-{{ post.pk }}">
  {% with post_url=post.get_absolute_url %}
    {% if post.featured_image %}
      <img src="{{ post.featured_image.url }}">
    {% endif %}
    <h2 class="blog-post-title">
      <a href="{{ post_url }}">{{ post.title|safe }}</a>
    </h2>
    <p class="blog-post-meta">
      <span class="glyphicon glyphicon-calendar"></span>
      {{ post.creation_date.date }} by
      <span class="glyphicon glyphicon-user"></span>
      {{ post.author }}
    </p>
    <div class="entry clearfix">
      {{ post.content|more:post_url|linebreakshtml }}
    </div>
  {% endwith %}
</div>
{% endfor %}

arpstrap/templates/arpegio-blog/includes/sidebar.html
{% load arpegio_blog_tags %}
<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
  <div class="sidebar-module">
    <div class="input-group custom-search-form">
      <input type="text" class="form-control">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">
	  <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
  </div>
  <div class="sidebar-module">
    {% recent_posts %}
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="{{ arpegio.social_media.github.value }}">GitHub</a></li>
      <li><a href="{{ arpegio.social_media.twitter.value }}">Twitter</a></li>
      <li><a href="{{ arpegio.social_media.facebook.value }}">Facebook</a></li>
    </ol>
  </div>
</div><!-- /.blog-sidebar -->

arpstrap/templates/arpegio-blog/post_detail.html
{% extends 'arpegio-blog/base.html' %}
{% load arpegio_tags %}

{% block head %}
  {% with title=post.title|striptags|add:" - "|add:arpegio.general.site_name.value %}
    {{ block.super }}
  {% endwith %}
{% endblock %}

{% block main_content %}
<div class="col-sm-8 blog-main">
  <div class="blog-post" id="{{ post.pk }}">
    <h2 class="blog-post-title">{{ post.title|safe }}</h2>
    <p class="blog-post-meta">
      <span class="glyphicon glyphicon-calendar"></span>
      {{ post.creation_date.date }} by
      <span class="glyphicon glyphicon-user"></span>
      {{ post.author }}
    </p>
    <div class="entry clearfix">
        {{ post.content|linebreakshtml }}
    </div>
    <p class="blog-post-meta">
      <span class="glyphicon glyphicon-folder-open"></span>
      Posted in: {{ post.categories.all|join_link:", " }}
      <strong> | </strong>
      <span class="glyphicon glyphicon-comment"></span>
      {% if post.comment_set.count %}
        {{ post.comment_set.count }} Comment{{ post.comment_set.count|pluralize }}
      {% else %}
        No Comments
      {% endif %}
      <br>
      <span class="glyphicon glyphicon-tags"></span>
      Tags: {{ post.tags.all|join_link:", " }}
    </p>
  </div>
</div>
{% endblock %}

arpstrap/templates/arpegio-blog/post_list.html
{% extends 'arpegio-blog/base.html' %}

{% block head %}
  {% with title='Blog'|add:" - "|add:arpegio.general.site_name.value %}
    {{ block.super }}
  {% endwith %}
{% endblock %}

{% block main_content %}
<div class="col-sm-8 blog-main">
  {% include 'arpegio-blog/includes/posts_list.html' with posts=posts %}
  {% if is_paginated %}
    <nav>
      <ul class="pager">
        {% if page_obj.has_previous %}
          <li>
            <a href="{% url 'blog:blog' page=page_obj.previous_page_number %}">
              Older posts
            </a>
          </li>
        {% endif %}
        {% if page_obj.has_next %}
          <li>
            <a href="{% url 'blog:blog' page=page_obj.next_page_number %}">
              Newer posts
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
  </div>
{% endblock %}

arpstrap/templates/arpegio-core/footer.html
<div class="blog-footer">
  <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</div>

arpstrap/templates/arpegio-core/head.html
{% load staticfiles %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>{{ title }}</title>

<!-- Bootstrap core CSS -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{% static 'style.css' %}" rel="stylesheet">

arpstrap/templates/arpegio-core/header.html
<div class="blog-header">
  <div class="container">
      <h1 class="blog-title">
        <a href="{% url "blog:blog" %}">Arprstrap</a>
      </h1>
    <p class="lead blog-description">A nice blog made with Arpegio</p>
  </div>
</div>

arpstrap/templates/arpegio-core/scripts.html
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>